services:
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    restart: unless-stopped
    ports:
      - 4848:4848
    volumes:
      - /volume1/docker/config/tubesync:/config
      - /volume2/Download/youtube:/downloads
    environment:
      - TZ=Asia/Saigon
      - PUID=1000
      - PGID=1000