version: "3.5"
services:
  homebridge:
    image: oznu/homebridge:2022-11-14
    # image: oznu/homebridge:latest
    container_name: homebridge
    restart: always
    network_mode: host
    ports:
      - 8581:8581
    volumes:
      - /mnt/sda1/Config/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: 10mb
        max-file: "1"