version: "2"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    network_mode: bridge
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 8880:80/tcp
    volumes:
      - /mnt/sda1/Config/adguard/workdir:/opt/adguardhome/work
      - /mnt/sda1/Config/adguard/confdir:/opt/adguardhome/conf
    restart: unless-stopped