substitutions:
  name: esphome-all-function
  friendly_name: LD2410 & Bluetooth Scan

# BLUETOOTH PROXY
bluetooth_proxy:
   active: true

# TRACKING BLUETOOTH DEVICE
ble_client:
  - mac_address: 5B:29:57:72:67:59 #Bluetooth MAC
    id: itag_black #Bluetooth Device Name


esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

external_components:
  - source:
      type: git
      url: https://github.com/screekworkshop/custom_components_support_for_screek_1w
      ref: main
    components: [esp32, uart, ld2410] 

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

ota:
  - platform: esphome
    id: ota_esphome

# Enable logging
logger:

# Enable Home Assistant API
api:

captive_portal:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case Wi-Fi connection fails
  ap:
    ssid: "Ld2410 Fallback Hotspot"

# Web server setup for improv serial
web_server:

ld2410:
  id: ld2410_radar

uart:
  id: ld2410_uart
  tx_pin: GPIO4
  rx_pin: GPIO3
  baud_rate: 256000
  data_bits: 8
  stop_bits: 1
  parity: NONE


esp32_ble_tracker:

binary_sensor:
  - platform: template
    id: itag_black_button_state_helper
    filters:
      delayed_off: 500ms
    on_release:
      then:
        - if:
            condition:
              lambda: 'return !id(itag_black_button_doubleclick).state;'
            then:
              - logger.log: "Single button press detected!"
              - binary_sensor.template.publish:
                  id: itag_black_button
                  state: ON
              - binary_sensor.template.publish:
                  id: itag_black_button
                  state: OFF

  - platform: template
    id: itag_black_button
    name: "Itag Black button"
    filters:
      delayed_off: 200ms

  - platform: template
    id: itag_black_button_doubleclick
    name: "Itag Black button doubleclick"
    filters:
      delayed_off: 1000ms

  # LD2410 Sensors
  - platform: ld2410
    has_target:
      name: Radar Target
    has_moving_target:
      name: Radar Moving Target
    has_still_target:
      name: Radar Still Target

switch:
  - platform: ble_client
    ble_client_id: itag_black
    name: "Connect Itag Black"

button:
  - platform: template
    name: "Itag Black alert"
    on_press:
      - ble_client.ble_write:
          id: itag_black
          service_uuid: "1802"
          characteristic_uuid: "2a06"
          value: [0x01]
      - delay: 10s
      - ble_client.ble_write:
          id: itag_black
          service_uuid: "1802"
          characteristic_uuid: "2a06"
          value: [0x00]

sensor:
  - platform: template
    id: sys_esp_temperature
    name: ESP Temperature
    lambda: return temperatureRead();
    unit_of_measurement: °C
    device_class: TEMPERATURE
    update_interval: 30s
    entity_category: "diagnostic"
  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 10s
  - platform: wifi_signal 
    name: RSSI
    id: wifi_signal_db
    update_interval: 1s
    entity_category: "diagnostic"
  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: 'kB'
    state_class: measurement
    entity_category: "diagnostic"
  - platform: ld2410
    moving_distance:
      name: Moving Distance
      id: moving_distance
    still_distance:
      name: Still Distance
      id: still_distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
    light:
      name: Sun Light


  # Added sensor configurations for Itag Black
  - platform: ble_client
    id: itag_black_ble_button_logic
    type: characteristic
    ble_client_id: itag_black
    service_uuid: "ffe0"
    characteristic_uuid: "ffe1"
    notify: true
    update_interval: never
    on_notify:
      then:
        - if:
            condition:
              lambda: 'return !id(itag_black_button_state_helper).state;'
            then:
              - binary_sensor.template.publish:
                  id: itag_black_button_state_helper
                  state: ON
              - binary_sensor.template.publish:
                  id: itag_black_button_state_helper
                  state: OFF
            else:
              - binary_sensor.template.publish:
                  id: itag_black_button_doubleclick
                  state: ON
              - binary_sensor.template.publish:
                  id: itag_black_button_doubleclick
                  state: OFF

  - platform: ble_client
    type: characteristic
    ble_client_id: itag_black
    name: "Itag Black Battery"
    service_uuid: "180f"
    characteristic_uuid: "2a19"
    icon: "mdi:battery"
    unit_of_measurement: "%"

  - platform: ble_client
    type: rssi
    ble_client_id: itag_black
    name: "Itag Black RSSI"