substitutions:
  name: esp32-bluetooth-proxy-fd1190
  friendly_name: Bluetooth Proxy Bedroom
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic-c3.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: S3qYQKyTXaEHIWKNcy3sNpDBLd/a9sUV7ZPhG5qgpmQ=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
