esphome:
  name: ld2410_kitchen
  friendly_name: LD2410 Kitchen

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

ota:
  - platform: esphome
    id: ota_esphome

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "gkROOOAh0xAjCVobOvDVZfPfezQvMEaK9FT1UJEshVU="


captive_portal:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ld2410 Fallback Hotspot"
    password: "12345678"


ld2410:
  id: ld2410_radar
  
uart:
  id: ld2410_uart
  tx_pin: GPIO4
  rx_pin: GPIO3
  baud_rate: 256000
  data_bits: 8
  stop_bits: 1
  parity: NONE

#bluetooth_proxy:
#  active: true

esp32_ble_tracker:

ble_client:
  # Replace with the MAC address of your device.
  - mac_address: 5B:29:57:72:67:59
    id: itag_black

binary_sensor:
  - platform: ld2410
    has_target:
      name: Radar Target
      id: radar_has_target
    has_moving_target:
      name: Radar Moving Target
    has_still_target:
      name: Radar Still Target
  # BUTTON
  - platform: template
    id: black_button
    name: "Black iTag Button"
    filters:
      delayed_off: 200ms
  - platform: template
    id: fob_switch
    name: Fob Switch
  - platform: template
    id: fob1_btn
    on_multi_click:
    - timing:
        - ON for at most 0.2s
        - OFF for at least 1s
      then: #Single click action
        - binary_sensor.template.publish:
            id: fob_switch
            state: OFF
    - timing:
        - ON for at most 0.2s
        - OFF for at most 1s
        - ON for at most 0.2s
        - OFF for at most 1s
        - ON for at most 0.2s
        - OFF for at least 0.5s
      then: #Double click action
        - binary_sensor.template.publish:
            id: fob_switch
            state: ON

sensor:
# This entry registers and awaits notifications for the
# characteristic that signals button presses. Each time
# a notification is received, the corresponding binary_sensor
# is briefly toggled.
  - platform: ble_client
    type: characteristic
    ble_client_id: itag_black
    name: "Black iTag btn"
    service_uuid: 'ffe0'
    characteristic_uuid: 'ffe1'
    notify: true
    update_interval: never
    on_notify:
      then:
        - binary_sensor.template.publish:
            id: black_button
            state: ON
        - binary_sensor.template.publish:
            id: black_button
            state: OFF
# This entry queries the battery level. Some tags may not
# support this characteristic, you will see 'Unknown' in the
# HA frontend.
  - platform: ble_client
    type: characteristic
    ble_client_id: itag_black
    name: "Black iTag Battery"
    service_uuid: '180f'
    characteristic_uuid: '2a19'
    icon: 'mdi:battery'
    unit_of_measurement: '%'
# This entry queries polls the RSSI when the tag is connected.
  - platform: ble_client
    type: rssi
    ble_client_id: itag_black
    name: "Black iTag RSSI"

  - platform: ld2410
    moving_distance:
      name: Radar Moving Distance
      id: moving_distance
    still_distance:
      name: Radar Still Distance
      id: still_distance
    moving_energy:
      name: Radar Move Energy
    still_energy:
      name: Radar Still Energy
    detection_distance:
      name: Radar Detection Distance
      id: radar_detection_distance
    