# Home Assistant integration (MQTT discovery)
homeassistant: true

# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://172.16.0.61:1883'
  # MQTT server authentication, uncomment if required:
  user: leolion
  password: Q214119@i

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  port: /dev/ttyUSB0
  #adapter: deconz

frontend: true #set true để nhận cấu hình port từ container

#  port: 8081
  # IP address of the device running Zigbee2MQTT
#  host: 172.16.0.15

advanced:
  network_key: GENERATE
  pan_id: GENERATE
