# Home Assistant integration (MQTT discovery)
homeassistant: true

# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://172.16.0.61:1883'
  # MQTT server authentication, uncomment if required:
  user: leolion
  password: Q214119@i

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  port: /dev/ttyUSB0
  #adapter: deconz

frontend:
  # Optional, default 8080 or you can use your own as well.
  port: 8081
  # IP address of the device running Zigbee2MQTT
  #host: 192.168.88.11
  
advanced:
  network_key: GENERATE
  pan_id: GENERATE
